---
- hosts: all
  become: true

  tasks:
  - name: create image using war file
    command: docker build -t simple-devops-image
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image allomac/simple-devops-image

  - name: push image on to dockerhub
    command: docker push allomac/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image allomac/simple-devops-image
    ignore_errors: yes
