---
- hosts: all
  become: true
  vars:
    my_image: simple-devops-image
    my_container: allomac/simple-devops-container

  tasks:
  - name: stop if we have old docker container
    command: docker stop {{ my_container }}
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm {{ my_container }}
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi {{ my_image }}
    ignore_errors: yes
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'


#  - name: building docker image
#    command: docker build -t {{ image }} .
#    args:
#      chdir: /opt/docker

  - name: pull docker image from dockerhub
    command: docker pull {{ my_image }}

  - name: creating docker image
    command: docker run -d --name {{ my_container }} -p 8080:8080 {{ my_image }}

